# Generated by Django 3.0.2 on 2020-01-11 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shoppingcart_shoppingcartproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='totalPrice',
        ),
        migrations.AlterField(
            model_name='shoppingcartproduct',
            name='shoppingCart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.ShoppingCart'),
        ),
    ]
